One Hot Encoding using pandas

In [1]:
import pandas as pd

In [2]:
Dataset=['cat', 'dog', 'bird', 'dog', 'cat']


In [3]:
Dataset=pd.get_dummies(Dataset)

In [4]:
Dataset

bird    cat    dog
0  False   True  False
1  False  False   True
2   True  False  False
3  False  False   True
4  False   True  False

One Hot Encoding using sklearn

In [15]:
from sklearn.preprocessing import OneHotEncoder

# Example data reshaped as 2D array
data = ['cat', 'dog', 'bird', 'dog', 'cat']
data = [[x] for x in data]  # Reshape to 2D array

# Initialize and fit the encoder
encoder = OneHotEncoder(sparse_output=False)  # Use sparse_output=False for a dense array
one_hot_encoded = encoder.fit_transform(data)

print(one_hot_encoded)

# Display the categories
print(encoder.categories_)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[array(['bird', 'cat', 'dog'], dtype=object)]


In [13]:
import numpy as np

# Example data
data = ['cat', 'dog', 'bird', 'dog', 'cat']

# Find unique categories
categories = list(set(data))

# Create a one-hot encoded matrix
one_hot_encoded = np.zeros((len(data), len(categories)))

for i, val in enumerate(data):
    one_hot_encoded[i, categories.index(val)] = 1

print(one_hot_encoded)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
